### PR TITLE
Solution for #330 - Deprecate modules.raku.org

### PR DESCRIPTION
**Pull request by lizmat**

### CODE REVIEW

**Review by vrurg — APPROVED** [review]

**Comment by 2colours** [comment]
@codesections is there any reaason this PR cannot be merged? If there is, please report back, it has been pending for almost 3 months without a clear status.

**Comment by lizmat** [comment]
The problem is really that before this can actually be effectuated, research must be done for the redirecting logic, and then code / configuration will need to be written.

**Comment by 2colours** [comment]
Thank you for the feedback. Knowing about the status of an issue is always better than just waiting for something to happen.

Is there something us mere mortals could do to help the process?

**Comment by lizmat** [comment]
Figure out the redirect rules that would need to be put in place at modules.raku.org  :-)

**Review by JJ — APPROVED** [review]
:+1:

**Comment by 2colours** [comment]
I originally came here to accelerate the transition but as explained in https://github.com/Raku/problem-solving/issues/330, I've grown to realize modules.raku.org was somewhat underrated.

As time passes with no considerable process on this issue, and raku.land developing slowly but surely in a somewhat isolated fashion on GitLab, I'd advise an alternation of the solution that I believe could be easier to implement and would leave the Raku community in a more flexible situation: do not remove and archive the module site, just advertise raku.land over it, and add a kind of banner that says something along the lines of "this site is frozen for the time being, you might want to check out this other cool site (being raku.land) that gets the job done, written in plain Raku".

The advantages I can think of are:
- raku.land still gets more showtime, which it indeed deserves
- no heavy modifications required on an administrative and infrastructure level: just push and deploy a little alternation to the content. Maybe a big disclaimer could be added to the README, although I don't fear someone would mistakenly start contributing to modules.raku.org...
- the good parts of modules.raku.org still remain in front of people's eyes - the concept of module Todo, Citation index, some badges, mentioning module adoptation, etc. Things I didn't know were a thing before I seriously checked that site out.
- the "nationalization" vs "outsourcing" polemy could be avoided. This could get a whole different post in my opinion... long story short, on one hand it doesn't seem nice to take control over someone's own project as an "official authority" - on the other hand, making a "private" project official has certain risks: it influences accessibility and maintenance doesn't have the same guarantees of continuity that a "community-owned project" could.

The way I understand, the only reasons to deprecate modules.raku.org are that:
- it's not being actively maintained
- it relies on Perl 5 and the Mojolicious framework in particular

Now, the thing is... I think these are two related problems. Basically, the second point keeps me from addressing the first point. However, supposedly it's not that hard, and [there was even an issue for it](https://github.com/Raku/modules.raku.org/issues/121) around the time it really started "dying down".

I can't promise that I can solve this issue (let alone on my own) but since I can see the deprecation itself is barely progressing, if at all, I would say, please, let's buy me, and the community in general, some time, by not making that deprecation permanent. That site has actual values and it's already under the ownership of "the community" as an entity. Don't throw this away. I don't think it's in the way of anyone, or raku.land itself.

**Review by codesections — APPROVED** [review]

**Comment by dontlaugh** [comment]
If the owners of raku.land are cool with it, and assuming modules.raku.org only hosts a website and not an API, a redirect rule can be set in Cloudflare quite easily. Cloudflare will pipe the traffic, so no one needs to host this redirect in an nginx/caddy/apache server.

In the meantime, I will continue trying to deploy the current site. See https://github.com/Raku/modules.raku.org/pull/147

**Comment by jjatria** [comment]
I think @dontlaugh's question was raised before, and back then ([in September last year](https://github.com/Raku/problem-solving/issues/330#issuecomment-1190059991)) @JRaspass and I already said that we were happy with a redirect. That feeling hasn't changed since then. As far as we are concerned, there is no blocker to that option.

---

In response to @2colours, however, I have to say that I find the whole approach a little frustrating. Both in the presentation [made recently and at the Raku Conference](https://www.youtube.com/watch?v=bBdPEBgZoDg) and in his comment on this thread, he talks about the two options being for the Raku community to "take [the project] away from the creators" or to "outsource" it to what in effect (and implied by his words) would be a "third party". This is entirely uncalled for.

Last time I checked, both @JRaspass and I were _part_ of the Raku community. And we wrote raku.land _for_ the Raku community. We wrote it because we saw the same problems that he saw with modules.raku.org. Why _his_ attempt at addressing them is "community-driven" and _ours_ isn't is beyond me.

So I reject both of those "alternatives".

There is no outsourcing, because whether @2colours likes it or not, raku.land _is_ a community-driven project: it was started by members of the community, for the use by the community, and it's entirely managed in public, facing the community.

If there are ways in which this can be improved, then let's do it. Is it the fact it's on GitLab that makes it not a community project? Then let's move it to GH. Is it that it's under its own org? That can be changed too. Why not. Is it the links in the footer? The branding of the site? The search bar? Let's change the whole lot. All you have to do is talk to us.

Which I guess brings me to the other alternative: there is no taking it away from us. Because - unless the intention is to veto @JRaspass and I from working on the site - if the community embraces raku.land, then _it hasn't changed owners_.

These feelings were present back when we discussed #330 in the first place, and back then I already mentioned that anyone who missed any feature from modules.raku.org (@2colours included) was welcome to add them or request for them to be added to raku.land. That there would be no blocker from us.

There are still no blockers from us, and that invitation is still open.

But I'd ask for everyone in this conversation to _please_ drop the language implying that raku.land is not a community project, and by extension that @JRaspass and I are somehow disconnected from this community.

**Comment by dontlaugh** [comment]
I've added a static redirect in Cloudflare for now. cc @andinus

**Comment by patrickbkr** [comment]
@jjatria 
> In response to @2colours, however, I have to say that I find the whole approach a little frustrating. Both in the presentation [made recently and at the Raku Conference](https://www.youtube.com/watch?v=bBdPEBgZoDg) and in his comment on this thread, he talks about the two options being for the Raku community to "take [the project] away from the creators" or to "outsource" it to what in effect (and implied by his words) would be a "third party". This is entirely uncalled for.
> 
> Last time I checked, both @JRaspass and I were _part_ of the Raku community. And we wrote raku.land _for_ the Raku community. We wrote it because we saw the same problems that he saw with modules.raku.org. Why _his_ attempt at addressing them is "community-driven" and _ours_ isn't is beyond me.
> 
> So I reject both of those "alternatives".
> 
> There is no outsourcing, because whether @2colours likes it or not, raku.land _is_ a community-driven project: it was started by members of the community, for the use by the community, and it's entirely managed in public, facing the community.

I haven't seen the presentation yet, but up until now I assumed this was merely about how it looks from the outside, i.e. modules.raku.org being priviledged by being a raku.org subdomain, while raku.land didn't have that favor. Also that modules.raku.org has no maintainer anymore and is now "only maintained by the community" i.e. is not really maintained at all.

I firmly reject any notion to challenge the ownership of raku.land. This is obviously your project. (It's opensource software with all the implications, but it's still obviously your project.) Also there is no reason whatsoever why you shouldn't be part of the Raku community. You are!

Also: Thanks for doing this! I am very grateful for how raku.land has improved our module ecosystem story.

> If there are ways in which this can be improved, then let's do it. Is it the fact it's on GitLab that makes not a community project? The let's move it to GH. Is that it's under its own org? That can be changed too. Why not. Is it the links in the footer? The branding of the site? The search bar? Let's change the whole lot. All you have to do is talk to us.
> 
> Which I guess brings me to the other alternative: there is no taking it away from us. Because - unless the intention is to veto @JRaspass and I from working on the site - if the community embraces raku.land, then _it hasn't changed owners_.

I do encourage you to keep raku.land at it's own domain (I do really like the flair of "raku.land") and keep the source at Gitlab. I do like diversity in how we develop software. Not feeling cozy at first because a project simply uses a different hoster from the one one is used to is a price everyone should be willing to pay. (I for one fell in love with sourcehut and have put all my recent projects there. *That's* a different experience.)

**Comment by codesections** [comment]
>  And we wrote raku.land for the Raku community. We wrote it because we saw the same problems that he saw with modules.raku.org. … raku.land is a community-driven project: it was started by members of the community, for the use by the community, and it's entirely managed in public, facing the community.

I agree 100%.

One way to make this clearer to everyone would be to add a copyright notice indicating that the copyright to raku.land is held by the Raku Foundation (/TPRF/TPF/YAS) the way [rakudo does](https://github.com/rakudo/rakudo#rakudo).  That, of course, wouldn't effect your status as the *maintainer* of raku.land, but it would make it perfectly clear that it's a community project (and not subject to dual-licensing, etc. – i.e., I'd say that Comma is _not_ a community project, even though it's one that the Raku community greatly appreciates!)

(IIUC the copyright notice can be in the `README` the way Rakudo does it, or it could be in a separate `COPYING` file in the project root)

**Comment by jjatria** [comment]
> I do like diversity in how we develop software.

@patrickbkr I think that's also been part of our idea as well. The day we _require_ the code to live in a specific host is the day we become vulnerable to that provider going away.

> One way to make this clearer to everyone would be to add a copyright notice indicating that the copyright to raku.land is held by the Raku Foundation (/TPRF/TPF/YAS) the way [rakudo does](https://github.com/rakudo/rakudo#rakudo)

Interesting. I just noticed that I don't think there _is_ a clear copyright on raku.land anywhere, although I'm not sure the copyright should be with TPRF or some sort of "Raku Land contributors" or something along those lines. This sounds like a good conversation to have. Maybe we should pick it up on IRC or on a RL issue?

**Comment by 2colours** [comment]
> In response to @2colours, however, I have to say that I find the whole approach a little frustrating. Both in the presentation [made recently and at the Raku Conference](https://www.youtube.com/watch?v=bBdPEBgZoDg) and in his comment on this thread, he talks about the two options being for the Raku community to "take [the project] away from the creators" or to "outsource" it to what in effect (and implied by his words) would be a "third party". This is entirely uncalled for.

Well, I also find it "a little frustrating" that the whole point went unnoticed, while raku.land is basically stagnating for years. You host the source code on Gitlab that basically no Raku-related projects use, the infra team has little to do with the whole thing, and in practice, nobody seems to be getting involved. Moreover, I have already said that the old site had a much more community-oriented look and feel. In the light of this, the whole redirect was a rather drastic measure (I guess I can't just go to modules.raku.org to confirm some behavior anymore).

> I firmly reject any notion to challenge the ownership of raku.land. This is obviously your project

So _yes, we are basically outsourcing a fundamental site_. Doesn't matter who is "a part of the Raku community", if it's "their project", then it's not a community-owned project, with basically no continuation plans or no more formal kind of entitlement to maintenance.  
It has happened on several occasions that somebody just walked away, confer the perl6.party situation after the departure of Zoffix Znet; we will probably never be able to fully recover all those links. I really don't know what is so strange about having a good deal of suspicion when some of the most depended-upon parts of the "Rakuverse" is suddenly "your project", whoever "you" may be.

> These feelings were present back when we discussed #330 in the first place, and back then I already mentioned that anyone who missed any feature from modules.raku.org (@2colours included) was welcome to add them or request for them to be added to raku.land. That there would be no blocker from us.

You seem to be well aware of the points I have raised - they are also fairly visible in this particular PR - and there are also recurring points, like prioritizing exact matches in the search, or doing something with the "popular dists" list (there are duplicates even, and the whole idea of using stars - do all git providers even have stars? - came with the problems of ecosystem shifts). So please, let's not pretend the elephant snuck into the room just yesterday. It's not like we didn't bring up plenty of suggestions.

A couple of years back, it seemed fair to assume that raku.land will surpass the old modules site in no time. If anything, it's less convincing the way it is today; it actually didn't fulfill this promise, yet it gets pushed more now, and I already get this impression that if one doesn't buy into it and proactively invest into it, it's somewhat blamed on them. You know, you are not the only one who creates stuff for the community, for example [CIAvash literally created a new site from scratch](https://github.com/Raku/problem-solving/issues/158). As much as I feel sorry for him because I think his overall activity has been under-appreciated over time, it is not a law of nature that people will immediately buy into your work so I hope you don't mind but I don't like this whole thing with shoving raku.land onto our faces, and for all I know, I didn't demand any sort of investment or maintenance burden on anyone. I just have to witness that my plans are sailing away as usual, and you are even throwing this proud tone at me.

**Comment by patrickbkr** [comment]
@2colours
> Well, I also find it "a little frustrating" that the whole point went unnoticed, while raku.land is basically stagnating for years.

This is not true. While modules.raku.org didn't have any maintainer for years, raku.land [enjoys a steady flow of commits](https://gitlab.com/raku-land/raku-land/-/commits/master).

> You host the source code on Gitlab that basically no Raku-related projects use,

I once again reject the notion that we as a community impose any restrictions on what hoster projects should use. I do want the ecosystem to become more diverse.

>  the infra team has little to do with the whole thing, and in practice,

 I also can not relate to the idea of giving projects different statuses, i.e. "not maintained by the infra team". I believe James Raspass has done a great job keeping the site up and stable.

> nobody seems to be getting involved.

This is not an issue with raku.land whatsoever. The Raku community as a whole has difficulty attracting contributors. Compared to many other projects in the Raku ecosystem raku.land is one of the alive projects. Also it *is* an open source project that does welcome contributions from the outside. Just as an example: Ciavash has added the dark color scheme to raku.land a year ago.

> Moreover, I have already said that the old site had a much more community-oriented look and feel. In the light of this, the whole redirect was a rather drastic measure (I guess I can't just go to modules.raku.org to confirm some behavior anymore).

This was an emergency measure caused by a server outage that lasted several days. The question that is left: In the light of this PR, do we want to revive modules.raku.org or just leave it as it is?
Also: If someone wants to pick modules.raku.org up again and start working on the site, I welcome that person to do so.

> 
> > I firmly reject any notion to challenge the ownership of raku.land. This is obviously your project
> 
> So _yes, we are basically outsourcing a fundamental site_. Doesn't matter who is "a part of the Raku community", if it's "their project", then it's not a community-owned project, with basically no continuation plans or no more formal kind of entitlement to maintenance. It has happened on several occasions that somebody just walked away, confer the perl6.party situation after the departure of Zoffix Znet; we will probably never be able to fully recover all those links. I really don't know what is so strange about having a good deal of suspicion when some of the most depended-upon parts of the "Rakuverse" is suddenly "your project", whoever "you" may be.

Ironically modules.raku.org was Zoffix' project and it basically got unmaintained with him leaving.
Can you please elaborate on what you think the difference between a community-owned project, a "their" project and an official project is? It seems you see a relevant difference that I do not see.

Also please note that by making this difference you are discriminating and did make at least me and jjatria feel uncomfortable.

> 
> > These feelings were present back when we discussed #330 in the first place, and back then I already mentioned that anyone who missed any feature from modules.raku.org (@2colours included) was welcome to add them or request for them to be added to raku.land. That there would be no blocker from us.
> 
> You seem to be well aware of the points I have raised - they are also fairly visible in this particular PR - and there are also recurring points, like prioritizing exact matches in the search, or doing something with the "popular dists" list (there are duplicates even, and the whole idea of using stars - do all git providers even have stars? - came with the problems of ecosystem shifts). So please, let's not pretend the elephant snuck into the room just yesterday. It's not like we didn't bring up plenty of suggestions.
> 
> A couple of years back, it seemed fair to assume that raku.land will surpass the old modules site in no time. If anything, it's less convincing the way it is today; it actually didn't fulfill this promise, yet it gets pushed more now, and I already get this impression that if one doesn't buy into it and proactively invest into it, it's somewhat blamed on them. You know, you are not the only one who creates stuff for the community, for example [CIAvash literally created a new site from scratch](https://github.com/Raku/problem-solving/issues/158). As much as I feel sorry for him because I think his overall activity has been under-appreciated over time, it is not a law of nature that people will immediately buy into your work so I hope you don't mind but I don't like this whole thing with shoving raku.land onto our faces, and for all I know, I didn't demand any sort of investment or maintenance burden on anyone. I just have to witness that my plans are sailing away as usual, and you are even throwing this proud tone at me.

raku.land, just like everything else in the Raku ecosystem, including modules.raku.org, Rakudo, MoarVM, the infra team and everything else there is is volunteer work. There is no obligation by anyone to work on things. I do think jjatria and raspass have reason to be proud of their work. That modules.raku.org has some features that raku.land doesn't have doesn't change this.
It seems you are attacking the raku.land people for "shoving raku.land onto our faces" while they were not the ones proposing or even supporting the deprecation of modules.raku.org.

**Comment by 2colours** [comment]
> This is not true. While modules.raku.org didn't have any maintainer for years, raku.land [enjoys a steady flow of commits](https://gitlab.com/raku-land/raku-land/-/commits/master).
> 
> >

I don't think this is a good metrics. The flow of commits may be steady but what the users actually see is basically the same for years for both sites. I have been trying to get to modules.raku.org for quite some time; unfortunately, I'm an absolute potato to OG Perl and there was always something that seemed more urgent or feasible. In the meantime, no additional presentation got added to raku.land, the search still doesn't prioritize exact matches, traversing dependencies has a partial solution, and some of those commits really correspond to fixes that just worked on modules.raku.org. Now, if something isn't on raku.land, I can't even visit modules.raku.org to confirm; this is one of my pain points. 

Anyway, let me repeat: it seemed to be an implicit premise (promise?) that while modules.raku.org is "dead", raku.land will gradually address all the shortcomings it originally had, and honestly, this is not what I see. Whether this is the reason the migration wasn't really pushed recently is not for me to decide but I think the observation shouldn't be neglected at the very least.


> I once again reject the notion that we as a community impose any restrictions on what hoster projects should use. I do want the ecosystem to become more diverse.
> 
>
> I also can not relate to the idea of giving projects different statuses, i.e. "not maintained by the infra team". I believe James Raspass has done a great job keeping the site up and stable.
> 
> >

Again, these points only stand if we really acknowledge that this fundamental project has been outsourced. For me, the one and only web interface to the ecosystem is NOT a part of the ecosystem. It's more than that. The stakes are much higher. Ironically, as you say, the Raku sites have been a good example why you shouldn't outsource your essential sites to volunteering individuals. For years, basically nobody has done anything for the raku.org site either (and when somebody did create a brand new site, indecisiveness got in the way). Now, I've been working on making raku.org at least maintainable from the technical point of view; I think I've talked about that as well in that notorious presentation, and frankly, it doesn't feel great that I get called out for anything in that presentation.

I think understanding the difference between "maintained by the community" and some individual's volunteer project should be easy. If the volunteering individuals disappear for any unfortunate reason (it could even be an accident), it will be a really hard problem to do anything with the legacy. If there is at least a kind of "formal" work group behind it, like the infra team and the doc team work, it's much safer because more effort goes into knowledge sharing and accessibility towards the community. The project is much less of a black box and it's much easier to even advertise it towards "outsiders" when some help is needed. There are stronger continuity guarantees.

> Also please note that by making this difference you are discriminating and did make at least me and jjatria feel uncomfortable.

I still don't know how it's discriminative to say that there is a difference between "owned by the community" as an entity, and between somebody's individual volunteer effort that can be blown away much more easier, _despite anybody's best intentions and work_. I didn't mean to offend anybody.

I hope you also don't mean to offend me because for what it's worth, I also feel very uncomfortable, especially after the tone jjatria used. I made my stance very clear about this situation long ago, and I did a presentation about my ideas and work regarding maintainability of Raku-related tools, content and services. Now, people who supposedly "were not the ones proposing or even supporting the deprecation of modules.raku.org" seem to call me out for an opinion that I have held for a very long time very openly, and I tried to reiterate countless times that I _only don't support the outright replacement_ of modules.raku.org, a site I'm actively seeking an opportunity to revive, rather than making anybody do any sort of investment.

So on my side, I do feel attacked by that comment, if we have to go with this narrative. In my head, it's a little bit strange that I was open about my opinion and always willing to clarify, and somebody who supposedly was so humble that they never really wanted this change to happen, suddenly calls me out, and all because of a presentation I did in good faith. This is not the way I want to sort any sort of problem out.

**Comment by lizmat** [comment]
Closing this PR as modules.raku.org did not survive the crash at its hosting location.

**Comment by jubilatious1** [comment]
So [modules.raku.org](http://modules.raku.org/) redirects to https://raku.land now?

**Comment by lizmat** [comment]
Has been for the past months at least

**Pull request closed without merging**
