### PR TITLE
Solution for #263, formal request for The Raku Foundation

### PR DESCRIPTION
**Pull request by lizmat**

### CODE REVIEW

**Comment by lizmat** [comment]
Finally, after a fresh clone, it seems to not carry with stray commits with it

**Review by codesections — APPROVED** [review]

**Review by vrurg — APPROVED** [review]

**Review by lizmat — COMMENTED** [review]
I approve of this PR, but cannot actually approve it  :-)

**Review by jnthn — APPROVED** [review]

**Comment by duncand** [comment]
So a DBA, and not a fully separate entity, is what we've ended up with deciding on?  Ok.

**Review by JJ — APPROVED** [review]
Thanks!

**Review by rba — APPROVED** [review]

**Comment by lizmat** [comment]
@duncand Yes, a DBA, if YAS agrees.    If so, it is a good starting point to figure out future options without too much pressure.  If not, then there'll be no choice but to set up a separate foundation.

**Review by vrurg — APPROVED** [review]

**Review by maettu — APPROVED** [review]

**Review by JJ — APPROVED** [review]

**Review by MasterDuke17 — APPROVED** [review]

**Pull request merged**
